line-length = 120
cache-dir = "~/.cache/ruff"
exclude = [".venv", "code/tests", "docs", "scripts"]
target-version = "py311"

[lint]
select = ["ALL"]
ignore = [
    "PLR0913",
    "D104",
    "D105",
    "D107",
    "B028",
    "S603",
    "S607",
    "PLR2004",
    "ANN204",
    "ANN002",
    "ANN003",
    "FBT",
    "TD",
    "FIX",
    "G004",
    # formatter does not support:
    "COM812",
    "ISC001",
]
unfixable = [
    "ERA", # don't delete commented out code automatically
    "T20", # don't delete prints automatically
]

[lint.pydocstyle]
convention = "google"

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.flake8-annotations]
suppress-none-returning = true

[lint.isort]
known-first-party = ["foundry_dev_tools", "transforms"]
